name: ci
on: push
jobs:
  gcloud-image-gpr:
    name: Push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: matts966/kubernetes-cloudflare-syncer/gcloud
          tag_with_ref: true
          dockerfile: Dockerfile
          cache_froms: matts966/kubernetes-cloudflare-syncer/gcloud:latest
          path: ./pkg/gcloud/

  gcloud-image-ghcr:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: matts966/kubernetes-cloudflare-syncer/gcloud:latest
          tag: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
          dockerfile: Dockerfile
          directory: ./pkg/gcloud/

  gke-image-gpr:
    name: Push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: matts966/kubernetes-cloudflare-syncer/gke
          tag_with_ref: true
          dockerfile: Dockerfile
          cache_froms: matts966/kubernetes-cloudflare-syncer/gke:latest
          path: ./pkg/gke/

  gke-image-ghcr:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: matts966/kubernetes-cloudflare-syncer/gke:latest
          tag: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
          dockerfile: Dockerfile
          directory: ./pkg/gke/
